name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Install rpm-build
        run: |
          sudo apt-get update
          sudo apt-get install rpm

      - name: Run clean install
        run: mvn clean install -Dskip.rpm=false
      
      - name: Create Draft Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "target/mtgacollection*.rpm"
          draft: true
