name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      
      - name: Install rpm-build
        run: |
          sudo apt-get update
          sudo apt-get install rpm

      - name: Run clean install
        run: mvn clean install -Dskip.rpm=false
      
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          prerelease: true
          files: |
            target/mtgacollection*.rpm
